#!/usr/bin/env python3
"""
Czech ↔ English scientific terminology table.

This is the core asset of KucLab Hertz. Measurement on the base Qwen3.5-9B:

    MMLU-Pro STEM (physics/chem/bio/math)   88.7%   ← already excellent
    Czech terminology  CS→EN                85.5%
    Czech terminology  EN→CS                66.1%   ← broken

Sample of what the base model actually produced:
    výkon               → "Moc"
    endotermická reakce → "exotermická reakce"   (the opposite!)
    oxidační číslo      → "Oxidacionní číslo"    (not a word)
    poločas rozpadu     → "polčas rozpadu"       (that's a sports half-time)
    hybnost             → "impuls"

So the model knows the science and cannot name it in Czech. That is the gap
this table closes.

TRAIN / EVAL SPLIT
------------------
Every 4th term (index % 4 == 3) is held out and never enters training data, so
`bench_czech_terms.py` measures whether the model generalised to Czech
scientific language — not whether it memorised this list.

Fields: (czech, english, domain, czech one-line definition)
"""
from __future__ import annotations

# ── Physics ────────────────────────────────────────────────────────────────
PHYSICS: list[tuple[str, str, str, str]] = [
    ("hybnost", "momentum", "fyzika", "součin hmotnosti a rychlosti, p = m·v; v izolované soustavě se zachovává"),
    ("kinetická energie", "kinetic energy", "fyzika", "energie pohybu, E_k = ½·m·v²"),
    ("potenciální energie", "potential energy", "fyzika", "energie polohy v silovém poli, tíhová E_p = m·g·h"),
    ("výkon", "power", "fyzika", "práce vykonaná za jednotku času, P = W/t, jednotka watt"),
    ("mechanická práce", "work", "fyzika", "W = F·s·cos α, jednotka joule"),
    ("setrvačnost", "inertia", "fyzika", "vlastnost tělesa setrvávat v klidu nebo rovnoměrném přímočarém pohybu"),
    ("tření", "friction", "fyzika", "odporová síla proti pohybu, F_t = f·F_n"),
    ("valivý odpor", "rolling resistance", "fyzika", "odpor při valení tělesa po podložce, mnohem menší než smykové tření"),
    ("vztlaková síla", "buoyant force", "fyzika", "Archimédův zákon: F = ρ·V·g, rovná se tíze vytlačené kapaliny"),
    ("dostředivá síla", "centripetal force", "fyzika", "síla mířící do středu kruhové dráhy, F = m·v²/r"),
    ("odstředivá síla", "centrifugal force", "fyzika", "zdánlivá setrvačná síla v rotující neinerciální soustavě"),
    ("Coriolisova síla", "Coriolis force", "fyzika", "setrvačná síla v rotující soustavě, stáčí pohyb; způsobuje rotaci cyklón"),
    ("moment síly", "torque", "fyzika", "M = F·r·sin α, otáčivý účinek síly, jednotka newtonmetr"),
    ("moment setrvačnosti", "moment of inertia", "fyzika", "míra odporu tělesa vůči změně rotačního pohybu"),
    ("úhlová rychlost", "angular velocity", "fyzika", "ω = Δφ/Δt, jednotka rad·s⁻¹"),
    ("těžiště", "centre of mass", "fyzika", "bod, v němž lze soustředit celou hmotnost tělesa"),
    ("tuhost pružiny", "spring constant", "fyzika", "k v Hookově zákoně F = k·x, jednotka N·m⁻¹"),
    ("kmitání", "oscillation", "fyzika", "periodický pohyb kolem rovnovážné polohy"),
    ("perioda", "period", "fyzika", "doba jednoho kmitu nebo oběhu, T = 1/f"),
    ("frekvence", "frequency", "fyzika", "počet kmitů za sekundu, jednotka hertz"),
    ("amplituda", "amplitude", "fyzika", "největší výchylka z rovnovážné polohy"),
    ("rezonance", "resonance", "fyzika", "prudký nárůst amplitudy, když budicí frekvence odpovídá vlastní"),
    ("tlumení", "damping", "fyzika", "postupný pokles amplitudy kmitů vlivem ztrát energie"),
    ("vlnová délka", "wavelength", "fyzika", "vzdálenost dvou sousedních vrcholů vlny, λ = v/f"),
    ("interference", "interference", "fyzika", "skládání vlnění; může být konstruktivní nebo destruktivní"),
    ("difrakce", "diffraction", "fyzika", "ohyb vlnění za překážkou nebo štěrbinou"),
    ("polarizace", "polarisation", "fyzika", "omezení kmitů příčného vlnění do jedné roviny"),
    ("stojaté vlnění", "standing wave", "fyzika", "vlnění s pevnými uzly a kmitnami, vzniká interferencí"),
    ("Dopplerův jev", "Doppler effect", "fyzika", "změna pozorované frekvence při vzájemném pohybu zdroje a pozorovatele"),
    ("rychlost zvuku", "speed of sound", "fyzika", "ve vzduchu při 20 °C asi 343 m·s⁻¹"),
    ("intenzita elektrického pole", "electric field strength", "fyzika", "síla na jednotkový náboj, E = F/Q, jednotka V·m⁻¹"),
    ("elektrický náboj", "electric charge", "fyzika", "základní vlastnost částic, jednotka coulomb"),
    ("elektrický proud", "electric current", "fyzika", "uspořádaný pohyb nosičů náboje, I = Q/t, jednotka ampér"),
    ("elektrické napětí", "voltage", "fyzika", "práce na přenesení jednotkového náboje, jednotka volt"),
    ("elektrický odpor", "electrical resistance", "fyzika", "Ohmův zákon R = U/I, jednotka ohm"),
    ("rezistivita", "resistivity", "fyzika", "měrný elektrický odpor materiálu, jednotka Ω·m"),
    ("vodivost", "conductance", "fyzika", "převrácená hodnota odporu, jednotka siemens"),
    ("kapacita", "capacitance", "fyzika", "schopnost kondenzátoru uchovat náboj, C = Q/U, jednotka farad"),
    ("indukčnost", "inductance", "fyzika", "schopnost cívky indukovat napětí při změně proudu, jednotka henry"),
    ("magnetická indukce", "magnetic flux density", "fyzika", "veličina popisující magnetické pole, jednotka tesla"),
    ("magnetický tok", "magnetic flux", "fyzika", "Φ = B·S·cos α, jednotka weber"),
    ("elektromagnetická indukce", "electromagnetic induction", "fyzika", "vznik napětí při změně magnetického toku (Faradayův zákon)"),
    ("střídavý proud", "alternating current", "fyzika", "proud periodicky měnící směr, v síti 50 Hz"),
    ("stejnosměrný proud", "direct current", "fyzika", "proud stálého směru"),
    ("impedance", "impedance", "fyzika", "zdánlivý odpor střídavého obvodu, komplexní veličina"),
    ("transformátor", "transformer", "fyzika", "mění napětí střídavého proudu pomocí elektromagnetické indukce"),
    ("polovodič", "semiconductor", "fyzika", "látka s vodivostí mezi vodičem a izolantem, např. křemík"),
    ("dioda", "diode", "fyzika", "součástka propouštějící proud jen jedním směrem"),
    ("supravodivost", "superconductivity", "fyzika", "stav s nulovým odporem a vypuzením magnetického pole"),
    ("vnitřní energie", "internal energy", "fyzika", "součet kinetické a potenciální energie všech částic tělesa"),
    ("teplo", "heat", "fyzika", "energie přenesená mezi tělesy vlivem rozdílu teplot"),
    ("měrná tepelná kapacita", "specific heat capacity", "fyzika", "teplo na ohřátí 1 kg látky o 1 K, jednotka J·kg⁻¹·K⁻¹"),
    ("skupenské teplo tání", "latent heat of fusion", "fyzika", "teplo potřebné k roztavení 1 kg látky bez změny teploty"),
    ("entropie", "entropy", "fyzika", "míra neuspořádanosti, S = k_B·ln W; v izolované soustavě neklesá"),
    ("enthalpie", "enthalpy", "fyzika", "H = U + p·V, tepelný obsah soustavy za stálého tlaku"),
    ("izotermický děj", "isothermal process", "fyzika", "děj za stálé teploty"),
    ("izobarický děj", "isobaric process", "fyzika", "děj za stálého tlaku"),
    ("izochorický děj", "isochoric process", "fyzika", "děj za stálého objemu"),
    ("adiabatický děj", "adiabatic process", "fyzika", "děj bez výměny tepla s okolím"),
    ("účinnost", "efficiency", "fyzika", "poměr užitečné a dodané energie, η = W/Q"),
    ("ideální plyn", "ideal gas", "fyzika", "model plynu splňující p·V = n·R·T"),
    ("tlak", "pressure", "fyzika", "p = F/S, jednotka pascal"),
    ("hustota", "density", "fyzika", "ρ = m/V, jednotka kg·m⁻³"),
    ("povrchové napětí", "surface tension", "fyzika", "síla působící v povrchu kapaliny, jednotka N·m⁻¹"),
    ("viskozita", "viscosity", "fyzika", "míra vnitřního tření kapaliny"),
    ("index lomu", "refractive index", "fyzika", "n = c/v, poměr rychlosti světla ve vakuu a v prostředí"),
    ("odraz", "reflection", "fyzika", "úhel odrazu se rovná úhlu dopadu"),
    ("lom světla", "refraction", "fyzika", "změna směru paprsku na rozhraní, Snellův zákon"),
    ("úplný odraz", "total internal reflection", "fyzika", "při překročení mezního úhlu se paprsek zcela odrazí; princip optického vlákna"),
    ("ohnisko", "focal point", "fyzika", "bod, kde se sbíhají paprsky rovnoběžné s optickou osou"),
    ("ohnisková vzdálenost", "focal length", "fyzika", "vzdálenost ohniska od čočky nebo zrcadla"),
    ("spojka", "converging lens", "fyzika", "čočka, která svazek paprsků sbíhá"),
    ("rozptylka", "diverging lens", "fyzika", "čočka, která svazek paprsků rozbíhá"),
    ("spektrum", "spectrum", "fyzika", "rozklad záření podle vlnových délek"),
    ("foton", "photon", "fyzika", "kvantum elektromagnetického záření o energii E = h·f"),
    ("fotoelektrický jev", "photoelectric effect", "fyzika", "uvolňování elektronů z látky dopadajícím zářením"),
    ("výstupní práce", "work function", "fyzika", "minimální energie k uvolnění elektronu z povrchu kovu"),
    ("černé těleso", "black body", "fyzika", "ideální zářič pohlcující veškeré dopadající záření"),
    ("vlnová funkce", "wave function", "fyzika", "komplexní funkce popisující kvantový stav částice"),
    ("princip neurčitosti", "uncertainty principle", "fyzika", "Δx·Δp ≥ ℏ/2; polohu a hybnost nelze současně přesně určit"),
    ("superpozice", "superposition", "fyzika", "kvantový stav jako souběh více stavů zároveň"),
    ("kvantové provázání", "quantum entanglement", "fyzika", "korelace stavů částic nezávislá na vzdálenosti"),
    ("spin", "spin", "fyzika", "vlastní moment hybnosti částice, čistě kvantová veličina"),
    ("elektronová slupka", "electron shell", "fyzika", "energetická hladina, na které se elektron v atomu nachází"),
    ("ionizační energie", "ionisation energy", "fyzika", "energie nutná k odtržení elektronu z atomu"),
    ("atomové jádro", "atomic nucleus", "fyzika", "jádro atomu tvořené protony a neutrony"),
    ("nukleon", "nucleon", "fyzika", "společný název pro proton a neutron"),
    ("izotop", "isotope", "fyzika", "atom téhož prvku s jiným počtem neutronů"),
    ("radioaktivita", "radioactivity", "fyzika", "samovolná přeměna nestabilních jader za vyzáření částic"),
    ("poločas rozpadu", "half-life", "fyzika", "doba, za kterou se rozpadne polovina jader vzorku"),
    ("jaderné štěpení", "nuclear fission", "fyzika", "rozpad těžkého jádra na lehčí za uvolnění energie"),
    ("jaderná fúze", "nuclear fusion", "fyzika", "slučování lehkých jader; zdroj energie hvězd"),
    ("hmotnostní schodek", "mass defect", "fyzika", "rozdíl hmotnosti jádra a součtu nukleonů, odpovídá vazebné energii"),
    ("vazebná energie", "binding energy", "fyzika", "energie potřebná k rozložení jádra na jednotlivé nukleony"),
    ("řetězová reakce", "chain reaction", "fyzika", "samoudržující se sled štěpných reakcí"),
    ("dilatace času", "time dilation", "fyzika", "zpomalení běhu času v pohybující se soustavě nebo v gravitačním poli"),
    ("kontrakce délek", "length contraction", "fyzika", "zkrácení délky tělesa ve směru pohybu při vysokých rychlostech"),
    ("vztažná soustava", "frame of reference", "fyzika", "soustava, vůči které popisujeme pohyb"),
    ("inerciální soustava", "inertial frame", "fyzika", "soustava, v níž platí zákon setrvačnosti"),
    ("úniková rychlost", "escape velocity", "fyzika", "v = √(2GM/R), rychlost k opuštění gravitačního pole"),
    ("gravitační zrychlení", "gravitational acceleration", "fyzika", "na Zemi asi 9,81 m·s⁻²"),
    ("rudý posuv", "redshift", "fyzika", "posun spektra ke kratším frekvencím; důkaz rozpínání vesmíru"),
    ("světelný rok", "light-year", "fyzika", "vzdálenost, kterou světlo urazí za rok, asi 9,46·10¹⁵ m"),
    ("černá díra", "black hole", "fyzika", "objekt s gravitací tak silnou, že z něj neunikne ani světlo"),
    ("plazma", "plasma", "fyzika", "ionizovaný plyn, čtvrté skupenství hmoty"),
    ("volný pád", "free fall", "fyzika", "pohyb pouze vlivem tíhové síly, bez odporu prostředí"),
    ("mezní úhel", "critical angle", "fyzika", "úhel dopadu, při němž nastává úplný odraz"),
]

# ── Chemistry ──────────────────────────────────────────────────────────────
CHEMISTRY: list[tuple[str, str, str, str]] = [
    ("mol", "mole", "chemie", "látkové množství obsahující 6,022·10²³ částic"),
    ("látkové množství", "amount of substance", "chemie", "veličina n měřená v molech"),
    ("molární hmotnost", "molar mass", "chemie", "hmotnost jednoho molu látky, jednotka g·mol⁻¹"),
    ("relativní atomová hmotnost", "relative atomic mass", "chemie", "bezrozměrný poměr hmotnosti atomu k atomové hmotnostní konstantě"),
    ("elektronegativita", "electronegativity", "chemie", "schopnost atomu přitahovat vazebné elektrony; nejvyšší má fluor"),
    ("oxidační číslo", "oxidation state", "chemie", "formální náboj atomu za předpokladu iontových vazeb"),
    ("valenční elektrony", "valence electrons", "chemie", "elektrony nejvyšší obsazené slupky, určují chemické vlastnosti"),
    ("kovalentní vazba", "covalent bond", "chemie", "vazba sdílením elektronového páru"),
    ("iontová vazba", "ionic bond", "chemie", "vazba elektrostatickou přitažlivostí opačně nabitých iontů"),
    ("kovová vazba", "metallic bond", "chemie", "vazba kationtů kovu sdíleným elektronovým plynem"),
    ("vodíková vazba", "hydrogen bond", "chemie", "mezimolekulová interakce H vázaného na F, O nebo N"),
    ("van der Waalsovy síly", "van der Waals forces", "chemie", "slabé mezimolekulové přitažlivé síly"),
    ("dipólový moment", "dipole moment", "chemie", "míra polarity molekuly"),
    ("kation", "cation", "chemie", "kladně nabitý ion vzniklý odtržením elektronu"),
    ("anion", "anion", "chemie", "záporně nabitý ion vzniklý přijetím elektronu"),
    ("disociace", "dissociation", "chemie", "rozpad látky na ionty, typicky ve vodném roztoku"),
    ("elektrolyt", "electrolyte", "chemie", "látka vedoucí v roztoku nebo tavenině elektrický proud"),
    ("rozpustnost", "solubility", "chemie", "maximální množství látky rozpustné v daném objemu rozpouštědla"),
    ("nasycený roztok", "saturated solution", "chemie", "roztok, v němž se za dané teploty už další látka nerozpustí"),
    ("sraženina", "precipitate", "chemie", "nerozpustná látka vylučující se z roztoku"),
    ("koncentrace", "concentration", "chemie", "látkové množství na jednotku objemu, jednotka mol·dm⁻³"),
    ("titrace", "titration", "chemie", "odměrné stanovení koncentrace reakcí se známým roztokem"),
    ("indikátor", "indicator", "chemie", "látka měnící barvu podle pH, např. fenolftalein"),
    ("neutralizace", "neutralisation", "chemie", "reakce kyseliny se zásadou za vzniku soli a vody"),
    ("pufr", "buffer", "chemie", "roztok tlumící změny pH, slabá kyselina a její sůl"),
    ("kyselina", "acid", "chemie", "látka odštěpující proton (Brønsted) nebo přijímající elektronový pár (Lewis)"),
    ("zásada", "base", "chemie", "látka přijímající proton"),
    ("hydroxid", "hydroxide", "chemie", "sloučenina obsahující skupinu OH⁻"),
    ("sůl", "salt", "chemie", "iontová sloučenina vzniklá neutralizací"),
    ("oxid", "oxide", "chemie", "binární sloučenina prvku s kyslíkem"),
    ("peroxid", "peroxide", "chemie", "sloučenina se skupinou −O−O−, kyslík má oxidační číslo −I"),
    ("exotermická reakce", "exothermic reaction", "chemie", "reakce uvolňující teplo do okolí, ΔH < 0"),
    ("endotermická reakce", "endothermic reaction", "chemie", "reakce spotřebovávající teplo z okolí, ΔH > 0"),
    ("aktivační energie", "activation energy", "chemie", "minimální energie nutná k zahájení reakce"),
    ("reakční rychlost", "reaction rate", "chemie", "změna koncentrace za jednotku času"),
    ("katalyzátor", "catalyst", "chemie", "látka snižující aktivační energii, sama se nespotřebuje"),
    ("inhibitor", "inhibitor", "chemie", "látka zpomalující chemickou reakci"),
    ("chemická rovnováha", "chemical equilibrium", "chemie", "stav, kdy rychlost přímé a zpětné reakce je stejná"),
    ("rovnovážná konstanta", "equilibrium constant", "chemie", "K, poměr koncentrací produktů a reaktantů v rovnováze"),
    ("oxidace", "oxidation", "chemie", "ztráta elektronů, zvýšení oxidačního čísla"),
    ("redukce", "reduction", "chemie", "přijetí elektronů, snížení oxidačního čísla"),
    ("oxidační činidlo", "oxidising agent", "chemie", "látka, která se sama redukuje a jiné oxiduje"),
    ("redukční činidlo", "reducing agent", "chemie", "látka, která se sama oxiduje a jiné redukuje"),
    ("elektrolýza", "electrolysis", "chemie", "rozklad látky průchodem stejnosměrného proudu"),
    ("galvanický článek", "galvanic cell", "chemie", "zdroj napětí využívající samovolnou redoxní reakci"),
    ("koroze", "corrosion", "chemie", "znehodnocování kovu chemickou reakcí s okolím"),
    ("hydrolýza", "hydrolysis", "chemie", "štěpení sloučeniny reakcí s vodou"),
    ("esterifikace", "esterification", "chemie", "reakce kyseliny s alkoholem za vzniku esteru a vody"),
    ("polymerace", "polymerisation", "chemie", "spojování monomerů do dlouhého řetězce polymeru"),
    ("polykondenzace", "polycondensation", "chemie", "polymerace za současného odštěpení malé molekuly, např. vody"),
    ("monomer", "monomer", "chemie", "základní stavební jednotka polymeru"),
    ("izomer", "isomer", "chemie", "sloučenina se stejným sumárním vzorcem, ale jiným uspořádáním atomů"),
    ("enantiomer", "enantiomer", "chemie", "zrcadlový izomer, který nelze ztotožnit s originálem"),
    ("chiralita", "chirality", "chemie", "vlastnost molekuly nebýt ztotožnitelná se svým zrcadlovým obrazem"),
    ("funkční skupina", "functional group", "chemie", "atom nebo skupina určující chemické vlastnosti sloučeniny"),
    ("uhlovodík", "hydrocarbon", "chemie", "sloučenina pouze z uhlíku a vodíku"),
    ("alkan", "alkane", "chemie", "nasycený uhlovodík s jednoduchými vazbami, CₙH₂ₙ₊₂"),
    ("alken", "alkene", "chemie", "uhlovodík s dvojnou vazbou, CₙH₂ₙ"),
    ("alkyn", "alkyne", "chemie", "uhlovodík s trojnou vazbou, CₙH₂ₙ₋₂"),
    ("aren", "arene", "chemie", "aromatický uhlovodík, např. benzen"),
    ("alkohol", "alcohol", "chemie", "sloučenina s hydroxylovou skupinou −OH"),
    ("aldehyd", "aldehyde", "chemie", "sloučenina se skupinou −CHO"),
    ("keton", "ketone", "chemie", "sloučenina s karbonylovou skupinou uvnitř řetězce"),
    ("karboxylová kyselina", "carboxylic acid", "chemie", "sloučenina se skupinou −COOH"),
    ("ester", "ester", "chemie", "produkt reakce kyseliny s alkoholem, skupina −COO−"),
    ("ether", "ether", "chemie", "sloučenina s kyslíkem mezi dvěma uhlovodíkovými zbytky"),
    ("amin", "amine", "chemie", "organická sloučenina odvozená od amoniaku"),
    ("aminokyselina", "amino acid", "chemie", "molekula s aminovou i karboxylovou skupinou, stavební jednotka bílkovin"),
    ("sacharid", "carbohydrate", "chemie", "cukr; polyhydroxyaldehyd nebo polyhydroxyketon"),
    ("lipid", "lipid", "chemie", "tuk nebo olej, ve vodě nerozpustná biomolekula"),
    ("bílkovina", "protein", "chemie", "polymer aminokyselin spojených peptidovou vazbou"),
    ("peptidová vazba", "peptide bond", "chemie", "vazba −CO−NH− mezi dvěma aminokyselinami"),
    ("denaturace", "denaturation", "chemie", "ztráta prostorové struktury bílkoviny teplem nebo pH"),
    ("periodická tabulka", "periodic table", "chemie", "uspořádání prvků podle rostoucího protonového čísla"),
    ("protonové číslo", "atomic number", "chemie", "počet protonů v jádře, značí se Z"),
    ("nukleonové číslo", "mass number", "chemie", "součet protonů a neutronů v jádře, značí se A"),
    ("halogen", "halogen", "chemie", "prvek 17. skupiny: F, Cl, Br, I, At"),
    ("vzácný plyn", "noble gas", "chemie", "prvek 18. skupiny s plnou valenční slupkou, prakticky nereaktivní"),
    ("alkalický kov", "alkali metal", "chemie", "prvek 1. skupiny, velmi reaktivní, tvoří kationty M⁺"),
    ("kov alkalických zemin", "alkaline earth metal", "chemie", "prvek 2. skupiny, např. hořčík nebo vápník"),
    ("přechodný kov", "transition metal", "chemie", "prvek 3.–12. skupiny se zaplňovanými d-orbitaly"),
    ("polokov", "metalloid", "chemie", "prvek s vlastnostmi mezi kovem a nekovem, např. křemík"),
    ("slitina", "alloy", "chemie", "směs kovu s dalším prvkem, např. mosaz nebo ocel"),
    ("krystalová mřížka", "crystal lattice", "chemie", "pravidelné prostorové uspořádání částic v krystalu"),
    ("amorfní látka", "amorphous solid", "chemie", "pevná látka bez pravidelné krystalové struktury, např. sklo"),
    ("sublimace", "sublimation", "chemie", "přechod z pevného skupenství přímo v plynné"),
    ("destilace", "distillation", "chemie", "dělení směsi podle rozdílných teplot varu"),
    ("filtrace", "filtration", "chemie", "oddělení pevné látky od kapaliny pomocí filtru"),
    ("krystalizace", "crystallisation", "chemie", "vylučování krystalů z roztoku nebo taveniny"),
    ("extrakce", "extraction", "chemie", "oddělení látky převedením do vhodného rozpouštědla"),
    ("chromatografie", "chromatography", "chemie", "dělení směsi podle rozdílné afinity k mobilní a stacionární fázi"),
    ("adsorpce", "adsorption", "chemie", "zachycení částic na povrchu pevné látky"),
    ("absorpce", "absorption", "chemie", "pohlcení látky celým objemem jiné látky"),
    ("suspenze", "suspension", "chemie", "heterogenní směs pevných částic v kapalině"),
    ("emulze", "emulsion", "chemie", "směs dvou nemísitelných kapalin, např. mléko"),
    ("koloid", "colloid", "chemie", "směs s částicemi velikosti 1–1000 nm"),
    ("mocenství", "valence", "chemie", "počet vazeb, které atom může vytvořit"),
    ("stechiometrie", "stoichiometry", "chemie", "výpočty látkových množství podle chemických rovnic"),
    ("Avogadrova konstanta", "Avogadro constant", "chemie", "6,022·10²³ mol⁻¹, počet částic v jednom molu"),
]

# ── Biology ────────────────────────────────────────────────────────────────
BIOLOGY: list[tuple[str, str, str, str]] = [
    ("buňka", "cell", "biologie", "základní stavební a funkční jednotka živých organismů"),
    ("buněčná stěna", "cell wall", "biologie", "pevný obal rostlinné buňky z celulózy"),
    ("cytoplazmatická membrána", "plasma membrane", "biologie", "polopropustný obal buňky z fosfolipidové dvojvrstvy"),
    ("cytoplazma", "cytoplasm", "biologie", "vnitřní obsah buňky mimo jádro"),
    ("jádro", "nucleus", "biologie", "organela obsahující DNA, řídí činnost buňky"),
    ("jadérko", "nucleolus", "biologie", "struktura v jádře, kde se skládají ribozomy"),
    ("ribozom", "ribosome", "biologie", "částice, na které probíhá syntéza bílkovin"),
    ("mitochondrie", "mitochondrion", "biologie", "organela produkující ATP buněčným dýcháním"),
    ("chloroplast", "chloroplast", "biologie", "organela rostlinné buňky, kde probíhá fotosyntéza"),
    ("endoplazmatické retikulum", "endoplasmic reticulum", "biologie", "síť membrán pro syntézu bílkovin a lipidů"),
    ("Golgiho aparát", "Golgi apparatus", "biologie", "organela třídící a balící bílkoviny"),
    ("lyzozom", "lysosome", "biologie", "váček s trávicími enzymy, štěpí odpad v buňce"),
    ("vakuola", "vacuole", "biologie", "váček se zásobami a odpadem, u rostlin velký a centrální"),
    ("cytoskelet", "cytoskeleton", "biologie", "vláknitá kostra buňky určující tvar a umožňující pohyb"),
    ("eukaryota", "eukaryote", "biologie", "organismus s buňkami majícími pravé jádro"),
    ("prokaryota", "prokaryote", "biologie", "organismus bez jádra, např. bakterie"),
    ("enzym", "enzyme", "biologie", "bílkovinný katalyzátor biochemických reakcí, vysoce specifický"),
    ("substrát", "substrate", "biologie", "látka, na kterou působí enzym"),
    ("aktivní místo", "active site", "biologie", "část enzymu, kde se váže substrát"),
    ("hormon", "hormone", "biologie", "látka přenášející signál mezi orgány krevní cestou"),
    ("homeostáza", "homeostasis", "biologie", "udržování stálého vnitřního prostředí organismu"),
    ("metabolismus", "metabolism", "biologie", "souhrn všech chemických přeměn v organismu"),
    ("katabolismus", "catabolism", "biologie", "rozkladné děje uvolňující energii"),
    ("anabolismus", "anabolism", "biologie", "syntetické děje spotřebovávající energii"),
    ("osmóza", "osmosis", "biologie", "difuze rozpouštědla přes polopropustnou membránu"),
    ("difuze", "diffusion", "biologie", "samovolné pronikání částic z vyšší koncentrace do nižší"),
    ("aktivní transport", "active transport", "biologie", "přenos látek proti koncentračnímu spádu za spotřeby ATP"),
    ("fagocytóza", "phagocytosis", "biologie", "pohlcení pevné částice buňkou"),
    ("turgor", "turgor pressure", "biologie", "tlak buněčného obsahu na stěnu, drží rostlinu vzpřímenou"),
    ("fotosyntéza", "photosynthesis", "biologie", "přeměna světelné energie na chemickou, 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂"),
    ("buněčné dýchání", "cellular respiration", "biologie", "oxidace glukózy na CO₂ a vodu se ziskem ATP"),
    ("kvašení", "fermentation", "biologie", "anaerobní rozklad cukru, vzniká etanol nebo kyselina mléčná"),
    ("chlorofyl", "chlorophyll", "biologie", "zelené barvivo pohlcující světlo při fotosyntéze"),
    ("transpirace", "transpiration", "biologie", "výdej vodní páry rostlinou průduchy"),
    ("průduch", "stoma", "biologie", "otvor v pokožce listu umožňující výměnu plynů"),
    ("DNA", "DNA", "biologie", "deoxyribonukleová kyselina, nositelka genetické informace"),
    ("RNA", "RNA", "biologie", "ribonukleová kyselina, přenáší a překládá genetickou informaci"),
    ("nukleotid", "nucleotide", "biologie", "stavební jednotka DNA: cukr, fosfát a dusíkatá báze"),
    ("dvoušroubovice", "double helix", "biologie", "prostorová struktura DNA ze dvou antiparalelních řetězců"),
    ("replikace", "replication", "biologie", "zdvojení DNA před dělením buňky, semikonzervativní"),
    ("transkripce", "transcription", "biologie", "přepis úseku DNA do mRNA"),
    ("translace", "translation", "biologie", "překlad mRNA do pořadí aminokyselin na ribozomu"),
    ("kodon", "codon", "biologie", "trojice bází mRNA kódující jednu aminokyselinu"),
    ("antikodon", "anticodon", "biologie", "trojice bází tRNA komplementární ke kodonu"),
    ("intron", "intron", "biologie", "nekódující úsek genu, při sestřihu se vystřihne"),
    ("exon", "exon", "biologie", "kódující úsek genu, který zůstává v zralé mRNA"),
    ("gen", "gene", "biologie", "úsek DNA nesoucí informaci pro znak nebo bílkovinu"),
    ("genom", "genome", "biologie", "veškerá genetická informace organismu"),
    ("chromozom", "chromosome", "biologie", "útvar z DNA a bílkovin nesoucí geny"),
    ("chromatin", "chromatin", "biologie", "rozvolněná forma DNA s bílkovinami v jádře"),
    ("alela", "allele", "biologie", "konkrétní varianta genu"),
    ("genotyp", "genotype", "biologie", "soubor genetické informace jedince"),
    ("fenotyp", "phenotype", "biologie", "soubor pozorovatelných znaků jedince"),
    ("homozygot", "homozygote", "biologie", "jedinec se dvěma stejnými alelami daného genu"),
    ("heterozygot", "heterozygote", "biologie", "jedinec se dvěma různými alelami daného genu"),
    ("dominantní alela", "dominant allele", "biologie", "alela projevující se i u heterozygota"),
    ("recesivní alela", "recessive allele", "biologie", "alela projevující se jen u homozygota"),
    ("mutace", "mutation", "biologie", "změna v sekvenci DNA; zdroj genetické variability"),
    ("mitóza", "mitosis", "biologie", "dělení tělní buňky na dvě geneticky shodné diploidní buňky"),
    ("meióza", "meiosis", "biologie", "redukční dělení tvořící čtyři haploidní pohlavní buňky"),
    ("crossing-over", "crossing over", "biologie", "výměna úseků mezi homologními chromozomy v profázi I"),
    ("haploidní", "haploid", "biologie", "s jednou sadou chromozomů, značí se n"),
    ("diploidní", "diploid", "biologie", "se dvěma sadami chromozomů, značí se 2n"),
    ("gameta", "gamete", "biologie", "pohlavní buňka, vajíčko nebo spermie"),
    ("zygota", "zygote", "biologie", "buňka vzniklá splynutím dvou gamet"),
    ("oplození", "fertilisation", "biologie", "splynutí samčí a samičí gamety"),
    ("evoluce", "evolution", "biologie", "postupná změna dědičných znaků populace v čase"),
    ("přirozený výběr", "natural selection", "biologie", "nenáhodné přežívání a rozmnožování lépe přizpůsobených jedinců"),
    ("adaptace", "adaptation", "biologie", "znak zvyšující zdatnost jedince v daném prostředí"),
    ("genetický drift", "genetic drift", "biologie", "náhodná změna četnosti alel, silná v malých populacích"),
    ("speciace", "speciation", "biologie", "vznik nového druhu"),
    ("rudimentární orgán", "vestigial organ", "biologie", "zakrnělý orgán bez původní funkce, např. slepé střevo"),
    ("homologní orgány", "homologous organs", "biologie", "orgány stejného původu, ale odlišné funkce"),
    ("konvergentní evoluce", "convergent evolution", "biologie", "nezávislý vznik podobných znaků u nepříbuzných druhů"),
    ("populace", "population", "biologie", "soubor jedinců téhož druhu na daném území"),
    ("ekosystém", "ecosystem", "biologie", "společenstvo organismů spolu s neživým prostředím"),
    ("biotop", "habitat", "biologie", "prostředí, ve kterém organismus žije"),
    ("potravní řetězec", "food chain", "biologie", "sled organismů, kde každý je potravou dalšího"),
    ("producent", "producer", "biologie", "organismus vytvářející organickou hmotu fotosyntézou"),
    ("konzument", "consumer", "biologie", "organismus živící se jinými organismy"),
    ("rozkladač", "decomposer", "biologie", "organismus rozkládající odumřelou organickou hmotu"),
    ("symbióza", "symbiosis", "biologie", "soužití dvou druhů, může být prospěšné i parazitické"),
    ("parazitismus", "parasitism", "biologie", "soužití, kde jeden druh získává na úkor druhého"),
    ("mutualismus", "mutualism", "biologie", "soužití prospěšné oběma druhům"),
    ("biodiverzita", "biodiversity", "biologie", "rozmanitost druhů a ekosystémů"),
    ("imunita", "immunity", "biologie", "schopnost organismu bránit se infekci"),
    ("protilátka", "antibody", "biologie", "bílkovina imunitního systému vážící se na antigen"),
    ("antigen", "antigen", "biologie", "látka vyvolávající imunitní odpověď"),
    ("lymfocyt", "lymphocyte", "biologie", "bílá krvinka zajišťující specifickou imunitu"),
    ("očkování", "vaccination", "biologie", "navození imunity předložením oslabeného nebo neškodného antigenu"),
    ("virus", "virus", "biologie", "nebuněčný infekční útvar množící se jen v hostitelské buňce"),
    ("bakterie", "bacterium", "biologie", "jednobuněčný prokaryotický organismus"),
    ("tkáň", "tissue", "biologie", "soubor buněk stejného typu a funkce"),
    ("orgán", "organ", "biologie", "část těla tvořená několika tkáněmi s určitou funkcí"),
    ("nerv", "nerve", "biologie", "svazek nervových vláken vedoucí vzruchy"),
    ("neuron", "neuron", "biologie", "nervová buňka vedoucí elektrický vzruch"),
    ("synapse", "synapse", "biologie", "spojení mezi neurony, kde se přenáší signál"),
    ("reflex", "reflex", "biologie", "nepodmíněná odpověď organismu na podnět"),
    ("cévní soustava", "circulatory system", "biologie", "soustava srdce a cév rozvádějící krev"),
]

# ── Mathematics ────────────────────────────────────────────────────────────
MATH: list[tuple[str, str, str, str]] = [
    ("derivace", "derivative", "matematika", "okamžitá rychlost změny funkce, směrnice tečny"),
    ("integrál", "integral", "matematika", "opak derivace; určitý integrál udává obsah plochy pod grafem"),
    ("primitivní funkce", "antiderivative", "matematika", "funkce F, pro kterou platí F' = f"),
    ("limita", "limit", "matematika", "hodnota, k níž se funkce blíží při daném průběhu argumentu"),
    ("spojitost", "continuity", "matematika", "funkce je spojitá v bodě, když se limita rovná funkční hodnotě"),
    ("asymptota", "asymptote", "matematika", "přímka, k níž se graf funkce neomezeně přibližuje"),
    ("extrém", "extremum", "matematika", "lokální maximum nebo minimum funkce"),
    ("inflexní bod", "inflection point", "matematika", "bod, kde funkce mění konvexitu"),
    ("konvexní funkce", "convex function", "matematika", "funkce, jejíž graf leží pod spojnicí libovolných dvou bodů"),
    ("monotonie", "monotonicity", "matematika", "vlastnost funkce být rostoucí nebo klesající"),
    ("definiční obor", "domain", "matematika", "množina všech přípustných vstupů funkce"),
    ("obor hodnot", "range", "matematika", "množina všech hodnot, kterých funkce nabývá"),
    ("inverzní funkce", "inverse function", "matematika", "funkce, která ruší účinek původní funkce"),
    ("složená funkce", "composite function", "matematika", "funkce vzniklá dosazením jedné funkce do druhé"),
    ("matice", "matrix", "matematika", "obdélníkové schéma čísel reprezentující lineární zobrazení"),
    ("determinant", "determinant", "matematika", "číslo přiřazené čtvercové matici; udává změnu objemu"),
    ("inverzní matice", "inverse matrix", "matematika", "matice A⁻¹ splňující A·A⁻¹ = I"),
    ("jednotková matice", "identity matrix", "matematika", "matice s jedničkami na diagonále a nulami jinde"),
    ("transpozice", "transpose", "matematika", "záměna řádků a sloupců matice"),
    ("hodnost matice", "rank", "matematika", "počet lineárně nezávislých řádků matice"),
    ("vlastní číslo", "eigenvalue", "matematika", "číslo λ splňující A·v = λ·v pro nenulový vektor v"),
    ("vlastní vektor", "eigenvector", "matematika", "vektor, jehož směr se lineárním zobrazením nemění"),
    ("vektor", "vector", "matematika", "veličina určená velikostí a směrem"),
    ("skalární součin", "dot product", "matematika", "a·b = |a|·|b|·cos φ, výsledkem je číslo"),
    ("vektorový součin", "cross product", "matematika", "součin dvou vektorů, výsledkem je kolmý vektor"),
    ("lineární nezávislost", "linear independence", "matematika", "žádný vektor nelze vyjádřit kombinací ostatních"),
    ("soustava rovnic", "system of equations", "matematika", "několik rovnic řešených současně"),
    ("Gaussova eliminace", "Gaussian elimination", "matematika", "metoda řešení soustav úpravou na trojúhelníkový tvar"),
    ("logaritmus", "logarithm", "matematika", "inverzní funkce k mocnině: log_a(x) = y právě když a^y = x"),
    ("přirozený logaritmus", "natural logarithm", "matematika", "logaritmus o základu e, značí se ln"),
    ("exponenciální funkce", "exponential function", "matematika", "funkce tvaru a^x, roste rychleji než každá mocnina"),
    ("mocnina", "power", "matematika", "opakované násobení téhož čísla, aⁿ"),
    ("odmocnina", "root", "matematika", "inverzní operace k mocnině"),
    ("absolutní hodnota", "absolute value", "matematika", "vzdálenost čísla od nuly, vždy nezáporná"),
    ("faktoriál", "factorial", "matematika", "n! = 1·2·…·n, počet permutací n prvků"),
    ("kombinace", "combination", "matematika", "výběr k prvků z n bez ohledu na pořadí, C(n,k) = n!/(k!(n−k)!)"),
    ("variace", "variation", "matematika", "výběr k prvků z n se zohledněním pořadí"),
    ("permutace", "permutation", "matematika", "uspořádání všech prvků množiny, počet je n!"),
    ("binomická věta", "binomial theorem", "matematika", "rozvoj (a+b)ⁿ pomocí kombinačních čísel"),
    ("prvočíslo", "prime number", "matematika", "přirozené číslo > 1 dělitelné jen jedničkou a sebou samým"),
    ("složené číslo", "composite number", "matematika", "přirozené číslo s více než dvěma děliteli"),
    ("největší společný dělitel", "greatest common divisor", "matematika", "největší číslo dělící obě zadaná čísla beze zbytku"),
    ("nejmenší společný násobek", "least common multiple", "matematika", "nejmenší číslo dělitelné oběma zadanými čísly"),
    ("dělitelnost", "divisibility", "matematika", "vlastnost čísla být beze zbytku dělitelné jiným"),
    ("zbytek po dělení", "remainder", "matematika", "co zbude při celočíselném dělení, operace modulo"),
    ("racionální číslo", "rational number", "matematika", "číslo zapsatelné jako podíl dvou celých čísel"),
    ("iracionální číslo", "irrational number", "matematika", "číslo nezapsatelné jako podíl celých čísel, např. √2 nebo π"),
    ("reálné číslo", "real number", "matematika", "číslo na číselné ose, racionální i iracionální"),
    ("komplexní číslo", "complex number", "matematika", "číslo tvaru a + bi, kde i² = −1"),
    ("imaginární jednotka", "imaginary unit", "matematika", "číslo i s vlastností i² = −1"),
    ("celé číslo", "integer", "matematika", "číslo bez desetinné části, kladné, záporné nebo nula"),
    ("přirozené číslo", "natural number", "matematika", "kladné celé číslo používané k počítání"),
    ("posloupnost", "sequence", "matematika", "uspořádaný seznam čísel indexovaný přirozenými čísly"),
    ("aritmetická posloupnost", "arithmetic sequence", "matematika", "každý člen vzniká přičtením konstantní diference d"),
    ("geometrická posloupnost", "geometric sequence", "matematika", "každý člen vzniká vynásobením konstantním kvocientem q"),
    ("řada", "series", "matematika", "součet členů posloupnosti"),
    ("konvergence", "convergence", "matematika", "vlastnost posloupnosti nebo řady mít konečnou limitu"),
    ("divergence", "divergence", "matematika", "vlastnost nemít konečnou limitu"),
    ("rovnice", "equation", "matematika", "zápis rovnosti dvou výrazů s neznámou"),
    ("nerovnice", "inequality", "matematika", "zápis nerovnosti dvou výrazů"),
    ("diskriminant", "discriminant", "matematika", "D = b² − 4ac, určuje počet řešení kvadratické rovnice"),
    ("kvadratická rovnice", "quadratic equation", "matematika", "rovnice tvaru ax² + bx + c = 0"),
    ("kořen rovnice", "root of an equation", "matematika", "hodnota neznámé, pro kterou rovnice platí"),
    ("polynom", "polynomial", "matematika", "výraz tvaru aₙxⁿ + … + a₁x + a₀"),
    ("mnohočlen", "polynomial expression", "matematika", "výraz složený ze součtu jednočlenů"),
    ("rozklad na součin", "factorisation", "matematika", "zápis výrazu jako součinu jednodušších činitelů"),
    ("úhel", "angle", "matematika", "část roviny vymezená dvěma polopřímkami"),
    ("obvod", "perimeter", "matematika", "délka hranice rovinného útvaru"),
    ("obsah", "area", "matematika", "velikost plochy rovinného útvaru"),
    ("objem", "volume", "matematika", "velikost prostoru zaujímaného tělesem"),
    ("povrch", "surface area", "matematika", "součet obsahů všech stěn tělesa"),
    ("přepona", "hypotenuse", "matematika", "nejdelší strana pravoúhlého trojúhelníku, naproti pravému úhlu"),
    ("odvěsna", "leg (of a right triangle)", "matematika", "strana pravoúhlého trojúhelníku přiléhající k pravému úhlu"),
    ("Pythagorova věta", "Pythagorean theorem", "matematika", "c² = a² + b² v pravoúhlém trojúhelníku"),
    ("těžnice", "median of a triangle", "matematika", "úsečka od vrcholu ke středu protější strany"),
    ("výška trojúhelníku", "altitude of a triangle", "matematika", "kolmice z vrcholu na protější stranu"),
    ("osa úhlu", "angle bisector", "matematika", "polopřímka dělící úhel na dvě shodné části"),
    ("kružnice", "circle", "matematika", "množina bodů se stejnou vzdáleností od středu"),
    ("kruh", "disc", "matematika", "kružnice včetně vnitřní plochy"),
    ("tětiva", "chord", "matematika", "úsečka spojující dva body kružnice"),
    ("tečna", "tangent line", "matematika", "přímka dotýkající se křivky v jediném bodě"),
    ("sečna", "secant line", "matematika", "přímka protínající křivku ve dvou bodech"),
    ("shodnost", "congruence", "matematika", "útvary jsou shodné, pokud mají stejný tvar i velikost"),
    ("podobnost", "similarity", "matematika", "útvary mají stejný tvar, ale různou velikost"),
    ("sinus", "sine", "matematika", "poměr protilehlé odvěsny k přeponě"),
    ("kosinus", "cosine", "matematika", "poměr přilehlé odvěsny k přeponě"),
    ("tangens", "tangent (function)", "matematika", "poměr protilehlé a přilehlé odvěsny, tg = sin/cos"),
    ("radián", "radian", "matematika", "úhel, jemuž přísluší oblouk délky rovné poloměru; 2π rad = 360°"),
    ("pravděpodobnost", "probability", "matematika", "poměr příznivých a všech možných výsledků, hodnota 0 až 1"),
    ("podmíněná pravděpodobnost", "conditional probability", "matematika", "P(A|B), pravděpodobnost A za předpokladu, že nastalo B"),
    ("Bayesova věta", "Bayes' theorem", "matematika", "P(A|B) = P(B|A)·P(A)/P(B), obrací podmíněnost"),
    ("náhodná veličina", "random variable", "matematika", "veličina, jejíž hodnota závisí na náhodném jevu"),
    ("střední hodnota", "expected value", "matematika", "vážený průměr hodnot náhodné veličiny"),
    ("rozptyl", "variance", "matematika", "průměr čtverců odchylek od střední hodnoty"),
    ("směrodatná odchylka", "standard deviation", "matematika", "odmocnina z rozptylu; míra rozptýlení dat kolem průměru"),
    ("medián", "median", "matematika", "prostřední hodnota seřazeného souboru, odolná vůči odlehlým hodnotám"),
    ("modus", "mode", "matematika", "nejčastěji se vyskytující hodnota souboru"),
    ("aritmetický průměr", "arithmetic mean", "matematika", "součet hodnot dělený jejich počtem"),
    ("normální rozdělení", "normal distribution", "matematika", "Gaussovo zvonovité rozdělení určené průměrem a odchylkou"),
    ("korelace", "correlation", "matematika", "míra lineární závislosti dvou veličin, hodnota −1 až 1"),
    ("množina", "set", "matematika", "souhrn navzájem různých objektů"),
    ("sjednocení", "union", "matematika", "množina prvků patřících alespoň do jedné z množin"),
    ("průnik", "intersection", "matematika", "množina prvků patřících do všech daných množin"),
    ("podmnožina", "subset", "matematika", "množina, jejíž všechny prvky patří i do jiné množiny"),
    ("prázdná množina", "empty set", "matematika", "množina neobsahující žádný prvek"),
    ("důkaz sporem", "proof by contradiction", "matematika", "důkaz předpokladem opaku a odvozením rozporu"),
    ("matematická indukce", "mathematical induction", "matematika", "důkaz platnosti pro všechna n z platnosti pro n a n+1"),
]

ALL_TERMS: list[tuple[str, str, str, str]] = PHYSICS + CHEMISTRY + BIOLOGY + MATH

# Every 4th term is held out — the benchmark must measure generalisation to
# Czech scientific language, not recall of a list we trained on.
HELD_OUT_EVERY = 4


def train_terms() -> list[tuple[str, str, str, str]]:
    return [t for i, t in enumerate(ALL_TERMS) if i % HELD_OUT_EVERY != HELD_OUT_EVERY - 1]


def eval_terms() -> list[tuple[str, str, str, str]]:
    return [t for i, t in enumerate(ALL_TERMS) if i % HELD_OUT_EVERY == HELD_OUT_EVERY - 1]


if __name__ == "__main__":
    tr, ev = train_terms(), eval_terms()
    print(f"total {len(ALL_TERMS)}  train {len(tr)}  held-out {len(ev)}")
    for name, lst in (("fyzika", PHYSICS), ("chemie", CHEMISTRY),
                      ("biologie", BIOLOGY), ("matematika", MATH)):
        print(f"  {name:<12} {len(lst)}")
    dupes = {}
    for cs, en, *_ in ALL_TERMS:
        dupes[cs] = dupes.get(cs, 0) + 1
    bad = {k: v for k, v in dupes.items() if v > 1}
    print("duplicate Czech terms:", bad or "none")
